In [1]:
import os, re, glob
#import cv2
import numpy as np
from keras.preprocessing import image
from PIL import Image
from keras.applications.imagenet_utils import preprocess_input

In [2]:
groups_folder_path = './resources/imgs/'
categories = ["AXISX2", "AXISX5", "AXISX6", "AXISX7"]
num_classes = len(categories)

In [3]:
image_w = 21
image_h = 21
X = []
Y = []

In [4]:
data_path = os.listdir(groups_folder_path)
print(data_path)
for filepath in categories:
    print(filepath)
    filepath = groups_folder_path + filepath
    files = os.listdir(filepath)
    for data in files:
        img_path = "{0}/{1}".format(filepath, data)
        img = image.load_img(img_path, target_size=(image_w, image_h))
        img_data = image.img_to_array(img)
        #img_data = np.expand_dims(img_data, axis=0)
        X.append(img_data)
        
        if '_AXISX_1' in data:
            Y.append(0)
        elif '_AXISX_2' in data:
            Y.append(1)
        elif '_AXISX_3' in data:
            Y.append(2)
        elif '_AXISX_4' in data:
            Y.append(3)
        elif '_AXISX_5' in data:
            Y.append(4)
        elif '_AXISX_6' in data:
            Y.append(5)
        elif '_AXISX_7' in data:
            Y.append(6)

['AXISX1', 'AXISX6', 'AXISX7', 'AXISX5', 'AXISX2', 'AXISX3', 'AXISX4']
AXISX2
AXISX5
AXISX6
AXISX7


In [5]:
print(X)
X.shape

[array([[[252., 252., 252.],
        [117., 117., 117.],
        [121., 121., 121.],
        ...,
        [255., 255., 255.],
        [179., 179., 179.],
        [ 65.,  65.,  65.]],

       [[203., 203., 203.],
        [167., 167., 167.],
        [163., 163., 163.],
        ...,
        [208., 208., 208.],
        [168., 168., 168.],
        [179., 179., 179.]],

       [[ 85.,  85.,  85.],
        [246., 246., 246.],
        [246., 246., 246.],
        ...,
        [ 52.,  52.,  52.],
        [208., 208., 208.],
        [255., 255., 255.]],

       ...,

       [[237., 237., 237.],
        [131., 131., 131.],
        [131., 131., 131.],
        ...,
        [246., 246., 246.],
        [163., 163., 163.],
        [121., 121., 121.]],

       [[239., 239., 239.],
        [131., 131., 131.],
        [131., 131., 131.],
        ...,
        [246., 246., 246.],
        [167., 167., 167.],
        [117., 117., 117.]],

       [[113., 113., 113.],
        [239., 239., 239.],
        [237., 

AttributeError: 'list' object has no attribute 'shape'

In [6]:
print(Y)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

In [7]:
X = np.array(X)
Y = np.array(Y)
print("{}, {}".format(X.shape, Y.shape))

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

print("{}, {}".format(X_train.shape, Y_train.shape))
print("{}, {}".format(X_test.shape, Y_test.shape))

(760, 21, 21, 3), (760,)
(570, 21, 21, 3), (570,)
(190, 21, 21, 3), (190,)


In [9]:
X_train.shape[3]

3

In [22]:
from keras.models import Sequential
from keras.layers import Dropout, Activation, Dense
from keras.layers import Flatten, Convolution2D, MaxPooling2D
from keras.models import load_model

In [ ]:
model.add(Conv2D(input_shape = (X_train.shape[1], X_train.shape[2], X_train.shape[3]), filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

# prior layer should be flattend to be connected to dense layers
model.add(Flatten())
# dense layer with 50 neurons
model.add(Dense(50, activation = 'relu'))
# final layer with 10 neurons to classify the instances
model.add(Dense(10, activation = 'relu'))

adam = optimizers.Adam(lr = 0.001)
model.compile(loss = 'rmse', optimizer = adam, metrics = ['accuracy'])


In [8]:
# Needed Library!
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 삽입!
import Cluster as c

In [9]:
X_reshape = X.reshape((X.shape[0], -1))
print(X_reshape.shape)
print(X_reshape)

(760, 1323)
[[252. 252. 252. ... 252. 252. 252.]
 [250. 250. 250. ... 250. 250. 250.]
 [252. 252. 252. ... 252. 252. 252.]
 ...
 [193. 193. 193. ... 193. 193. 193.]
 [197. 197. 197. ... 197. 197. 197.]
 [222. 222. 222. ... 222. 222. 222.]]


In [10]:
print(X_reshape)
X_reshape.shape

[[252. 252. 252. ... 252. 252. 252.]
 [250. 250. 250. ... 250. 250. 250.]
 [252. 252. 252. ... 252. 252. 252.]
 ...
 [193. 193. 193. ... 193. 193. 193.]
 [197. 197. 197. ... 197. 197. 197.]
 [222. 222. 222. ... 222. 222. 222.]]


(760, 1323)

In [11]:
result, scaled_x = c.kmeans(X_reshape, 4, normalization="none")

정규화 진행 안함--------
Scaled_dataset: 
[[252. 252. 252. ... 252. 252. 252.]
 [250. 250. 250. ... 250. 250. 250.]
 [252. 252. 252. ... 252. 252. 252.]
 ...
 [193. 193. 193. ... 193. 193. 193.]
 [197. 197. 197. ... 197. 197. 197.]
 [222. 222. 222. ... 222. 222. 222.]]


In [12]:
print(scaled_x)
print(result.labels_)

[[252. 252. 252. ... 252. 252. 252.]
 [250. 250. 250. ... 250. 250. 250.]
 [252. 252. 252. ... 252. 252. 252.]
 ...
 [193. 193. 193. ... 193. 193. 193.]
 [197. 197. 197. ... 197. 197. 197.]
 [222. 222. 222. ... 222. 222. 222.]]
[3 3 1 3 3 1 1 1 3 1 3 3 3 1 3 3 3 1 1 3 1 3 3 3 3 3 1 3 1 3 1 3 3 3 3 3 1
 1 1 1 3 3 3 3 1 1 1 1 1 1 1 3 1 3 1 3 1 1 3 1 1 1 3 3 3 3 3 3 3 1 3 3 3 3
 3 3 1 1 3 3 1 3 3 3 1 1 3 3 3 1 1 3 3 1 3 3 3 1 3 1 1 1 3 3 1 3 1 3 3 3 1
 1 1 3 1 3 3 3 3 3 3 1 1 1 1 3 3 3 1 3 3 3 3 3 3 1 1 3 1 3 3 1 3 3 1 1 3 3
 3 3 3 3 3 3 1 1 1 3 1 3 1 3 3 3 3 3 1 1 3 3 3 3 3 3 1 1 1 3 3 3 1 3 1 3 3
 1 1 1 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 2